services:
  backend:
    image: ghcr.io/stovoy/stovoy-dev-backend:latest
    restart: unless-stopped
    expose:
      - "8080"

  caddy:
    build:
      context: .
      target: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
