# Trunk configuration (minimal for now)


[build]
# The build target is the HTML entry‑point for the Yew application. Trunk will
# parse this file, discover the `<link data-trunk ...>` tags and manage the
# whole WebAssembly build pipeline automatically.
target = "frontend/index.html"

# Output directory (kept as‑is).
dist = "dist"

[serve]
port = 8081
