[package]
name = "stovoy-tech-static"
version = "0.1.0"
authors = ["Steve Mostovoy <stevemostovoysm@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "*", features = ["stdweb"] }
stdweb = "*"
