name: cargo-deny

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo install --locked cargo-deny
      - run: cargo deny --workspace check
