name: CI

on:
  push:
    branches: [main, master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install toolchain as defined in rust-toolchain.toml
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "rustfmt, clippy"

      - uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --exclude stovoy-tech-frontend -- -D warnings

      - name: Tests
        run: cargo test --workspace --all-targets --exclude stovoy-tech-frontend
