name: CI

on:
  push:
    branches: [main, master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install toolchain as defined in rust-toolchain.toml
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: "rustfmt, clippy"

      - uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --exclude stovoy-dev-frontend -- -D warnings

      - name: Tests
        run: cargo test --workspace --all-targets --exclude stovoy-dev-frontend

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Install Trunk and wasm target
        run: |
          cargo install trunk --locked
          rustup target add wasm32-unknown-unknown

      - name: Build static site
        run: trunk build --release --dist dist --public-url /

      - name: Install brotli
        run: sudo apt-get update && sudo apt-get install -y brotli

      - name: Brotli compress assets
        run: |
          find dist -type f \( -name '*.css' -o -name '*.js' -o -name '*.wasm' \) -exec brotli -f -q 11 {} \;
