name: commitlint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npx --yes @commitlint/cli --from=${{ github.event.pull_request.base.sha }} --to=${{ github.event.pull_request.head.sha }}
